easy_admin:
    entities:
        # List the entity class name you want to manage
        User:
          class: App\Entity\User
#        - App\Entity\Category
        #- App\Entity\User

    site_name: 'Mon Blog'
    new:
      title: 'Nouveau Utilisateur'
    edit:
      title: 'Modifier Utilisateur'