swiftmailer:
    url: '%env(MAILER_URL)%'
    transport: smtp
    host: localhost
    # host: smtp.gmail.com
    port: 1025
    username: '%env(username)%'
    password: '%env(password)%'
    spool: { type: 'memory' }
